/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as DispatchersRouteImport } from './routes/dispatchers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnKotlinIndexRouteImport } from './routes/learn-kotlin/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResumePrintRouteImport } from './routes/resume.print'
import { Route as LearnKotlinMindmapRouteImport } from './routes/learn-kotlin/mindmap'
import { Route as LearnKotlinTopicIdRouteImport } from './routes/learn-kotlin/$topicId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminResumeProjectsRouteImport } from './routes/admin/resume.projects'
import { Route as AdminResumeLanguagesRouteImport } from './routes/admin/resume.languages'
import { Route as AdminResumeHobbiesRouteImport } from './routes/admin/resume.hobbies'
import { Route as AdminResumeEducationRouteImport } from './routes/admin/resume.education'
import { Route as AdminResumeCertificatesRouteImport } from './routes/admin/resume.certificates'
import { Route as AdminPostsIdRouteImport } from './routes/admin/posts.$id'
import { Route as AdminResumeProjectsIdRouteImport } from './routes/admin/resume.projects.$id'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchersRoute = DispatchersRouteImport.update({
  id: '/dispatchers',
  path: '/dispatchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnKotlinIndexRoute = LearnKotlinIndexRouteImport.update({
  id: '/learn-kotlin/',
  path: '/learn-kotlin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumePrintRoute = ResumePrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ResumeRoute,
} as any)
const LearnKotlinMindmapRoute = LearnKotlinMindmapRouteImport.update({
  id: '/learn-kotlin/mindmap',
  path: '/learn-kotlin/mindmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnKotlinTopicIdRoute = LearnKotlinTopicIdRouteImport.update({
  id: '/learn-kotlin/$topicId',
  path: '/learn-kotlin/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResumeProjectsRoute = AdminResumeProjectsRouteImport.update({
  id: '/admin/resume/projects',
  path: '/admin/resume/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResumeLanguagesRoute = AdminResumeLanguagesRouteImport.update({
  id: '/admin/resume/languages',
  path: '/admin/resume/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResumeHobbiesRoute = AdminResumeHobbiesRouteImport.update({
  id: '/admin/resume/hobbies',
  path: '/admin/resume/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResumeEducationRoute = AdminResumeEducationRouteImport.update({
  id: '/admin/resume/education',
  path: '/admin/resume/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResumeCertificatesRoute = AdminResumeCertificatesRouteImport.update({
  id: '/admin/resume/certificates',
  path: '/admin/resume/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminResumeProjectsIdRoute = AdminResumeProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminResumeProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dispatchers': typeof DispatchersRoute
  '/resume': typeof ResumeRouteWithChildren
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/learn-kotlin/$topicId': typeof LearnKotlinTopicIdRoute
  '/learn-kotlin/mindmap': typeof LearnKotlinMindmapRoute
  '/resume/print': typeof ResumePrintRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/learn-kotlin': typeof LearnKotlinIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/resume/certificates': typeof AdminResumeCertificatesRoute
  '/admin/resume/education': typeof AdminResumeEducationRoute
  '/admin/resume/hobbies': typeof AdminResumeHobbiesRoute
  '/admin/resume/languages': typeof AdminResumeLanguagesRoute
  '/admin/resume/projects': typeof AdminResumeProjectsRouteWithChildren
  '/admin/resume/projects/$id': typeof AdminResumeProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dispatchers': typeof DispatchersRoute
  '/resume': typeof ResumeRouteWithChildren
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/learn-kotlin/$topicId': typeof LearnKotlinTopicIdRoute
  '/learn-kotlin/mindmap': typeof LearnKotlinMindmapRoute
  '/resume/print': typeof ResumePrintRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/learn-kotlin': typeof LearnKotlinIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/resume/certificates': typeof AdminResumeCertificatesRoute
  '/admin/resume/education': typeof AdminResumeEducationRoute
  '/admin/resume/hobbies': typeof AdminResumeHobbiesRoute
  '/admin/resume/languages': typeof AdminResumeLanguagesRoute
  '/admin/resume/projects': typeof AdminResumeProjectsRouteWithChildren
  '/admin/resume/projects/$id': typeof AdminResumeProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dispatchers': typeof DispatchersRoute
  '/resume': typeof ResumeRouteWithChildren
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/learn-kotlin/$topicId': typeof LearnKotlinTopicIdRoute
  '/learn-kotlin/mindmap': typeof LearnKotlinMindmapRoute
  '/resume/print': typeof ResumePrintRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/learn-kotlin/': typeof LearnKotlinIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/resume/certificates': typeof AdminResumeCertificatesRoute
  '/admin/resume/education': typeof AdminResumeEducationRoute
  '/admin/resume/hobbies': typeof AdminResumeHobbiesRoute
  '/admin/resume/languages': typeof AdminResumeLanguagesRoute
  '/admin/resume/projects': typeof AdminResumeProjectsRouteWithChildren
  '/admin/resume/projects/$id': typeof AdminResumeProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dispatchers'
    | '/resume'
    | '/services'
    | '/testimonials'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/learn-kotlin/$topicId'
    | '/learn-kotlin/mindmap'
    | '/resume/print'
    | '/admin'
    | '/blog'
    | '/learn-kotlin'
    | '/admin/posts/$id'
    | '/admin/resume/certificates'
    | '/admin/resume/education'
    | '/admin/resume/hobbies'
    | '/admin/resume/languages'
    | '/admin/resume/projects'
    | '/admin/resume/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dispatchers'
    | '/resume'
    | '/services'
    | '/testimonials'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/learn-kotlin/$topicId'
    | '/learn-kotlin/mindmap'
    | '/resume/print'
    | '/admin'
    | '/blog'
    | '/learn-kotlin'
    | '/admin/posts/$id'
    | '/admin/resume/certificates'
    | '/admin/resume/education'
    | '/admin/resume/hobbies'
    | '/admin/resume/languages'
    | '/admin/resume/projects'
    | '/admin/resume/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dispatchers'
    | '/resume'
    | '/services'
    | '/testimonials'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/learn-kotlin/$topicId'
    | '/learn-kotlin/mindmap'
    | '/resume/print'
    | '/admin/'
    | '/blog/'
    | '/learn-kotlin/'
    | '/admin/posts/$id'
    | '/admin/resume/certificates'
    | '/admin/resume/education'
    | '/admin/resume/hobbies'
    | '/admin/resume/languages'
    | '/admin/resume/projects'
    | '/admin/resume/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DispatchersRoute: typeof DispatchersRoute
  ResumeRoute: typeof ResumeRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LearnKotlinTopicIdRoute: typeof LearnKotlinTopicIdRoute
  LearnKotlinMindmapRoute: typeof LearnKotlinMindmapRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LearnKotlinIndexRoute: typeof LearnKotlinIndexRoute
  AdminResumeCertificatesRoute: typeof AdminResumeCertificatesRoute
  AdminResumeEducationRoute: typeof AdminResumeEducationRoute
  AdminResumeHobbiesRoute: typeof AdminResumeHobbiesRoute
  AdminResumeLanguagesRoute: typeof AdminResumeLanguagesRoute
  AdminResumeProjectsRoute: typeof AdminResumeProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatchers': {
      id: '/dispatchers'
      path: '/dispatchers'
      fullPath: '/dispatchers'
      preLoaderRoute: typeof DispatchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-kotlin/$topicId': {
      id: '/learn-kotlin/$topicId'
      path: '/learn-kotlin/$topicId'
      fullPath: '/learn-kotlin/$topicId'
      preLoaderRoute: typeof LearnKotlinTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-kotlin/mindmap': {
      id: '/learn-kotlin/mindmap'
      path: '/learn-kotlin/mindmap'
      fullPath: '/learn-kotlin/mindmap'
      preLoaderRoute: typeof LearnKotlinMindmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/print': {
      id: '/resume/print'
      path: '/print'
      fullPath: '/resume/print'
      preLoaderRoute: typeof ResumePrintRouteImport
      parentRoute: typeof ResumeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-kotlin/': {
      id: '/learn-kotlin/'
      path: '/learn-kotlin'
      fullPath: '/learn-kotlin'
      preLoaderRoute: typeof LearnKotlinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/resume/certificates': {
      id: '/admin/resume/certificates'
      path: '/admin/resume/certificates'
      fullPath: '/admin/resume/certificates'
      preLoaderRoute: typeof AdminResumeCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resume/education': {
      id: '/admin/resume/education'
      path: '/admin/resume/education'
      fullPath: '/admin/resume/education'
      preLoaderRoute: typeof AdminResumeEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resume/hobbies': {
      id: '/admin/resume/hobbies'
      path: '/admin/resume/hobbies'
      fullPath: '/admin/resume/hobbies'
      preLoaderRoute: typeof AdminResumeHobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resume/languages': {
      id: '/admin/resume/languages'
      path: '/admin/resume/languages'
      fullPath: '/admin/resume/languages'
      preLoaderRoute: typeof AdminResumeLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resume/projects': {
      id: '/admin/resume/projects'
      path: '/admin/resume/projects'
      fullPath: '/admin/resume/projects'
      preLoaderRoute: typeof AdminResumeProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resume/projects/$id': {
      id: '/admin/resume/projects/$id'
      path: '/$id'
      fullPath: '/admin/resume/projects/$id'
      preLoaderRoute: typeof AdminResumeProjectsIdRouteImport
      parentRoute: typeof AdminResumeProjectsRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/contact' {
  const createFileRoute: CreateFileRoute<
    '/contact',
    FileRoutesByPath['/contact']['parentRoute'],
    FileRoutesByPath['/contact']['id'],
    FileRoutesByPath['/contact']['path'],
    FileRoutesByPath['/contact']['fullPath']
  >
}
declare module './routes/dispatchers' {
  const createFileRoute: CreateFileRoute<
    '/dispatchers',
    FileRoutesByPath['/dispatchers']['parentRoute'],
    FileRoutesByPath['/dispatchers']['id'],
    FileRoutesByPath['/dispatchers']['path'],
    FileRoutesByPath['/dispatchers']['fullPath']
  >
}
declare module './routes/resume' {
  const createFileRoute: CreateFileRoute<
    '/resume',
    FileRoutesByPath['/resume']['parentRoute'],
    FileRoutesByPath['/resume']['id'],
    FileRoutesByPath['/resume']['path'],
    FileRoutesByPath['/resume']['fullPath']
  >
}
declare module './routes/services' {
  const createFileRoute: CreateFileRoute<
    '/services',
    FileRoutesByPath['/services']['parentRoute'],
    FileRoutesByPath['/services']['id'],
    FileRoutesByPath['/services']['path'],
    FileRoutesByPath['/services']['fullPath']
  >
}
declare module './routes/testimonials' {
  const createFileRoute: CreateFileRoute<
    '/testimonials',
    FileRoutesByPath['/testimonials']['parentRoute'],
    FileRoutesByPath['/testimonials']['id'],
    FileRoutesByPath['/testimonials']['path'],
    FileRoutesByPath['/testimonials']['fullPath']
  >
}
declare module './routes/admin/posts' {
  const createFileRoute: CreateFileRoute<
    '/admin/posts',
    FileRoutesByPath['/admin/posts']['parentRoute'],
    FileRoutesByPath['/admin/posts']['id'],
    FileRoutesByPath['/admin/posts']['path'],
    FileRoutesByPath['/admin/posts']['fullPath']
  >
}
declare module './routes/admin/projects' {
  const createFileRoute: CreateFileRoute<
    '/admin/projects',
    FileRoutesByPath['/admin/projects']['parentRoute'],
    FileRoutesByPath['/admin/projects']['id'],
    FileRoutesByPath['/admin/projects']['path'],
    FileRoutesByPath['/admin/projects']['fullPath']
  >
}
declare module './routes/admin/testimonials' {
  const createFileRoute: CreateFileRoute<
    '/admin/testimonials',
    FileRoutesByPath['/admin/testimonials']['parentRoute'],
    FileRoutesByPath['/admin/testimonials']['id'],
    FileRoutesByPath['/admin/testimonials']['path'],
    FileRoutesByPath['/admin/testimonials']['fullPath']
  >
}
declare module './routes/blog/$slug' {
  const createFileRoute: CreateFileRoute<
    '/blog/$slug',
    FileRoutesByPath['/blog/$slug']['parentRoute'],
    FileRoutesByPath['/blog/$slug']['id'],
    FileRoutesByPath['/blog/$slug']['path'],
    FileRoutesByPath['/blog/$slug']['fullPath']
  >
}
declare module './routes/learn-kotlin/$topicId' {
  const createFileRoute: CreateFileRoute<
    '/learn-kotlin/$topicId',
    FileRoutesByPath['/learn-kotlin/$topicId']['parentRoute'],
    FileRoutesByPath['/learn-kotlin/$topicId']['id'],
    FileRoutesByPath['/learn-kotlin/$topicId']['path'],
    FileRoutesByPath['/learn-kotlin/$topicId']['fullPath']
  >
}
declare module './routes/learn-kotlin/mindmap' {
  const createFileRoute: CreateFileRoute<
    '/learn-kotlin/mindmap',
    FileRoutesByPath['/learn-kotlin/mindmap']['parentRoute'],
    FileRoutesByPath['/learn-kotlin/mindmap']['id'],
    FileRoutesByPath['/learn-kotlin/mindmap']['path'],
    FileRoutesByPath['/learn-kotlin/mindmap']['fullPath']
  >
}
declare module './routes/resume.print' {
  const createFileRoute: CreateFileRoute<
    '/resume/print',
    FileRoutesByPath['/resume/print']['parentRoute'],
    FileRoutesByPath['/resume/print']['id'],
    FileRoutesByPath['/resume/print']['path'],
    FileRoutesByPath['/resume/print']['fullPath']
  >
}
declare module './routes/admin/index' {
  const createFileRoute: CreateFileRoute<
    '/admin/',
    FileRoutesByPath['/admin/']['parentRoute'],
    FileRoutesByPath['/admin/']['id'],
    FileRoutesByPath['/admin/']['path'],
    FileRoutesByPath['/admin/']['fullPath']
  >
}
declare module './routes/blog/index' {
  const createFileRoute: CreateFileRoute<
    '/blog/',
    FileRoutesByPath['/blog/']['parentRoute'],
    FileRoutesByPath['/blog/']['id'],
    FileRoutesByPath['/blog/']['path'],
    FileRoutesByPath['/blog/']['fullPath']
  >
}
declare module './routes/learn-kotlin/index' {
  const createFileRoute: CreateFileRoute<
    '/learn-kotlin/',
    FileRoutesByPath['/learn-kotlin/']['parentRoute'],
    FileRoutesByPath['/learn-kotlin/']['id'],
    FileRoutesByPath['/learn-kotlin/']['path'],
    FileRoutesByPath['/learn-kotlin/']['fullPath']
  >
}
declare module './routes/admin/posts.$id' {
  const createFileRoute: CreateFileRoute<
    '/admin/posts/$id',
    FileRoutesByPath['/admin/posts/$id']['parentRoute'],
    FileRoutesByPath['/admin/posts/$id']['id'],
    FileRoutesByPath['/admin/posts/$id']['path'],
    FileRoutesByPath['/admin/posts/$id']['fullPath']
  >
}
declare module './routes/admin/resume.certificates' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/certificates',
    FileRoutesByPath['/admin/resume/certificates']['parentRoute'],
    FileRoutesByPath['/admin/resume/certificates']['id'],
    FileRoutesByPath['/admin/resume/certificates']['path'],
    FileRoutesByPath['/admin/resume/certificates']['fullPath']
  >
}
declare module './routes/admin/resume.education' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/education',
    FileRoutesByPath['/admin/resume/education']['parentRoute'],
    FileRoutesByPath['/admin/resume/education']['id'],
    FileRoutesByPath['/admin/resume/education']['path'],
    FileRoutesByPath['/admin/resume/education']['fullPath']
  >
}
declare module './routes/admin/resume.hobbies' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/hobbies',
    FileRoutesByPath['/admin/resume/hobbies']['parentRoute'],
    FileRoutesByPath['/admin/resume/hobbies']['id'],
    FileRoutesByPath['/admin/resume/hobbies']['path'],
    FileRoutesByPath['/admin/resume/hobbies']['fullPath']
  >
}
declare module './routes/admin/resume.languages' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/languages',
    FileRoutesByPath['/admin/resume/languages']['parentRoute'],
    FileRoutesByPath['/admin/resume/languages']['id'],
    FileRoutesByPath['/admin/resume/languages']['path'],
    FileRoutesByPath['/admin/resume/languages']['fullPath']
  >
}
declare module './routes/admin/resume.projects' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/projects',
    FileRoutesByPath['/admin/resume/projects']['parentRoute'],
    FileRoutesByPath['/admin/resume/projects']['id'],
    FileRoutesByPath['/admin/resume/projects']['path'],
    FileRoutesByPath['/admin/resume/projects']['fullPath']
  >
}
declare module './routes/admin/resume.projects.$id' {
  const createFileRoute: CreateFileRoute<
    '/admin/resume/projects/$id',
    FileRoutesByPath['/admin/resume/projects/$id']['parentRoute'],
    FileRoutesByPath['/admin/resume/projects/$id']['id'],
    FileRoutesByPath['/admin/resume/projects/$id']['path'],
    FileRoutesByPath['/admin/resume/projects/$id']['fullPath']
  >
}

interface ResumeRouteChildren {
  ResumePrintRoute: typeof ResumePrintRoute
}

const ResumeRouteChildren: ResumeRouteChildren = {
  ResumePrintRoute: ResumePrintRoute,
}

const ResumeRouteWithChildren =
  ResumeRoute._addFileChildren(ResumeRouteChildren)

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminResumeProjectsRouteChildren {
  AdminResumeProjectsIdRoute: typeof AdminResumeProjectsIdRoute
}

const AdminResumeProjectsRouteChildren: AdminResumeProjectsRouteChildren = {
  AdminResumeProjectsIdRoute: AdminResumeProjectsIdRoute,
}

const AdminResumeProjectsRouteWithChildren =
  AdminResumeProjectsRoute._addFileChildren(AdminResumeProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DispatchersRoute: DispatchersRoute,
  ResumeRoute: ResumeRouteWithChildren,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  LearnKotlinTopicIdRoute: LearnKotlinTopicIdRoute,
  LearnKotlinMindmapRoute: LearnKotlinMindmapRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  LearnKotlinIndexRoute: LearnKotlinIndexRoute,
  AdminResumeCertificatesRoute: AdminResumeCertificatesRoute,
  AdminResumeEducationRoute: AdminResumeEducationRoute,
  AdminResumeHobbiesRoute: AdminResumeHobbiesRoute,
  AdminResumeLanguagesRoute: AdminResumeLanguagesRoute,
  AdminResumeProjectsRoute: AdminResumeProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
